---
- name: clone balacer-ui to /opt
  git:
    repo: https://github.com/trnila/stm32f429-balancer-ui.git
    dest: /opt/balancer-ui

- name: make install
  make:
    chdir: /opt/balancer-ui/ctrl_c
    target: install
  notify: restart frontend_ctrl
