---
- name: install golang
  package:
      name: golang
      state: present

- name: install git
  package:
      name: git
      state: present

- name: install balancer server
  shell: go get -u github.com/trnila/balancer_ctrl
  environment:
    GOPATH: /usr/local/share/go/
    GOBIN: /usr/local/bin
  notify: restart balancer_ctrl

- name: set cap_net_bind_service to balancer_ctrl binary so that we can run it on privileged port (ie 80)
  capabilities:
    path: /usr/local/bin/balancer_ctrl
    capability: cap_net_bind_service+ep

- name: copy balancer_ctrl.service
  template:
      src: templates/balancer_ctrl.service.j2
      dest: /etc/systemd/system/balancer_ctrl.service
  notify: restart balancer_ctrl

- name: enable balancer_ctrl at boot
  service:
    name: balancer_ctrl
    state: started
    enabled: yes

- import_tasks: wifi.yml
- import_tasks: firmware.yml
  when: FLASH_FIRMWARE|default(false)|bool
