---
- name: install hostapd
  package:
      name: hostapd
      state: present

- name: copy hostapd.conf
  template:
      src: templates/hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
  norift: restart hostapd

- name: enable configuration of hostapd
  lineinfile:
      path: /etc/default/hostapd
      regexp: '^#?DAEMON_CONF=.+'
      line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart hostapd

- name: enable hostapd at boot
  service:
    name: hostapd
    state: started
    enabled: yes


- name: install dnsmasq
  package:
      name: dnsmasq
      state: present

- name: enable dnsmasq at boot
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: static ip for wlan0
  blockinfile:
      path: /etc/dhcpcd.conf
      block: |
          interface wlan0
            static ip_address=10.10.10.1/24

- name: enable ip forwarding accross interfaces
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- package:
      name: iptables-persistent
      state: present

- template:
    src: files/rules.v4
    dest: /etc/iptables/rules.v4
  notify: reload iptables

- template:
    src: files/rules.v6
    dest: /etc/iptables/rules.v6
  notify: reload iptables

- lineinfile:
    path: /etc/hosts
    line: '10.10.10.1 balancer.local'

