---
- name: install hostapd
  package:
      name: hostapd
      state: present

- name: copy hostapd.conf
  template:
      src: templates/hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
  notify: restart hostapd

- name: enable configuration of hostapd
  lineinfile:
      path: /etc/default/hostapd
      regexp: '^#?DAEMON_CONF=.+'
      line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart hostapd

- name: enable hostapd at boot
  service:
    name: hostapd
    state: started
    enabled: yes

- name: install dnsmasq
  package:
      name: dnsmasq
      state: present

- name: enable dnsmasq at boot
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: static ip for wlan0
  blockinfile:
      path: /etc/dhcpcd.conf
      block: |
          interface wlan0
            static ip_address=10.10.10.1/24
            static ip6_address=fd64:cafe::1/64

- name: enable additional configuration of dnsmasq
  lineinfile:
      path: /etc/dnsmasq.conf
      line: conf-dir=/etc/dnsmasq.d/,*.conf

- name: setup dnsmasq dhcp address range
  copy:
      dest: /etc/dnsmasq.d/wlan0.conf
      content: |
          interface=wlan0
          dhcp-range=10.10.10.10,10.10.10.254,255.255.255.0,48h

- name: enable ip forwarding accross interfaces
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- package:
      name: iptables-persistent
      state: present

- template:
    src: files/rules.v4
    dest: /etc/iptables/rules.v4
  notify: reload iptables

- template:
    src: files/rules.v6
    dest: /etc/iptables/rules.v6
  notify: reload iptables

- lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
      - 'fd64:cafe::1 balancer.local'
      - '10.10.10.1 balancer.local'

- name: enable ipv6 forwarding accross interfaces
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: install radvd
  package:
      name: radvd
      state: present

- name: copy radvd.conf
  template:
      src: templates/radvd.conf.j2
      dest: /etc/radvd.conf.j2
  notify: restart radvd

- name: enable radvd at boot
  service:
    name: radvd
    state: started
    enabled: yes
