- name: restart balancer_ctrl
  listen: restart balancer_ctrl
  service: name="balancer_ctrl.service" state="restarted" daemon-reload="yes"

- name: restart hostapd
  listen: restart hostapd
  service: name="hostapd.service" state="restarted" daemon-reload="yes"

- name: restart radvd
  listen: restart radvd
  service: name="radvd.service" state="restarted" daemon-reload="yes"

- name: reload iptables
  listen: reload iptables
  shell: iptables-restore /etc/iptables/rules.v4

- name: reload iptables
  listen: reload iptables
  shell: ip6tables-restore /etc/iptables/rules.v6
